// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// dtw_
List dtw_(NumericMatrix x, NumericMatrix y, int window);
RcppExport SEXP DTW_dtw_(SEXP xSEXP, SEXP ySEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    __result = Rcpp::wrap(dtw_(x, y, window));
    return __result;
END_RCPP
}
